### ISSUE TITLE
[SETTING] 프로젝트 초기 세팅

### ISSUE THREAD

**Issue by gardening-y** [TeamDATEROAD/DATEROAD-SERVER#1]
## 🛠 Issue

프로젝트 초기 세팅을 진행합니다.

## 📝 To-do

- [x] Issue 템플릿 추가
- [x] PR 템플릿 추가
- [x] Label 생성
- [x] Branch Rule 설정
- [x] .gitignore 설정
- [x] 팀 AWS 계정 생성
- [x] 팀 Docker Hub 계정 생성
- [x] Docker 세팅
- [x] EC2 세팅
- [x] RDS 세팅
- [x] Nginx 세팅
- [x] Github Action CI/CD 세팅
- [x] 멀티 모듈 구조 분리
- [x] Readme 초안 작성

**Comment by rlarlgnszx** [comment]
갓든이 미쳤습니다. :100:
