### ISSUE TITLE
[FEAT] Amplitude를 위한 일부 API 응답 변경

### ISSUE THREAD

**Issue by gardening-y** [TeamDATEROAD/DATEROAD-SERVER#279]
## 🛠 Issue

Amplitude 도입을 위한 일부 API 응답 변경

## 📝 To-do

- [x] 코스 등록 API (user_point, user_course_count(유저가 등록한 코스 횟수))
- [x] 코스 열람 API (user_point, user_purchase_count(유저의 총 코스 구매 횟수), user_free_remained(유저의 무료 열람 횟수))
- [x] 데이트 일정 등록 API (date_schedule_num ( 다가오는 일정개수))
