### ISSUE TITLE
[REFACTOR] Point 내역 조회 API 

### ISSUE THREAD

**Issue by rlarlgnszx** [TeamDATEROAD/DATEROAD-SERVER#44]
## 🛠 Issue

Point 내역 조회 API - #41 수정 
## 📝 To-do

- [x] yyyy.MM.dd 형식으로 변경 
- [x] print 구문 지우기 
- [x] PointService 중복 메서드 추출 
- [x] Builder(access = AccessLevel.PRIVATE)

**Comment by rlarlgnszx** [comment]
끝!
