### ISSUE TITLE
[REFACTOR] 전체적인 코드 통일  관리

### ISSUE THREAD

**Issue by rlarlgnszx** [TeamDATEROAD/DATEROAD-SERVER#47]
## 🛠 Issue

전체적인 코드 통일  관리
## 📝 To-do

- [ ] @Builder(access = AccessLevel.PRIVATE)로 변경
- [ ] ResponseEntity.ok(Dto)로 변경
- [ ] 중복 메서드 추출 
- [ ] 팩토리 메소드로 변경
